version: '2'
services:

    apache5:
        container_name: varnish-apache5
        image         : php:5-apache
        volumes       :
            - ./html/apache5/:/var/www/html/

    apache7:
        container_name: varnish-apache7
        image         : php:7-apache
        volumes       :
            - ./html/apache7/:/var/www/html/

    varnish:
        container_name: varnish-server
        image         : million12/varnish
        volumes       :
            - ./varnish/:/etc/varnish/
        ports         :
            - 80:80
        links:
            - apache5
            - apache7